<?php

namespace AppBundle\Repository;

/**
 * aRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aRepository extends \Doctrine\ORM\EntityRepository
{
}
