<?php

namespace AppBundle\Repository;

/**
 * pRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pRepository extends \Doctrine\ORM\EntityRepository
{
}
