<?php

namespace tayara\AnnonceBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function nbAnoonce()
    {   $stat = $this->createQueryBuilder('t');
        $stat->select('count(t.id)');
       
        return$stat->getQuery()->getSingleScalarResult();
        
    }
    
       public function nbVehicule()
    {   $stat = $this->createQueryBuilder('t');
        $stat->select('count(t.id)');
        $stat1=$stat->where('t.categorie = 1');
    
        return $stat1->getQuery()->getSingleScalarResult();
        
    }
    
       public function nbImmobilier()
    {   $stat = $this->createQueryBuilder('t');
        $stat->select('count(t.id)');
        $stat1=$stat->where('t.categorie = 2');
    
        return $stat1->getQuery()->getSingleScalarResult();
        
    }
    
    
}
